name: upnp
version: 2.1.0
description: Universal Plugin and Play Host/Client
homepage: https://github.com/SpinlockLabs/upnp.dart
dependencies:
  xml: ^6.2.2
  crypto: "^3.0.1"
  collection: ^1.15.0-nullsafety.4
  http: ^1.2.2
environment:
  sdk: '>=3.0.0 <=4.0.0'

